name: Build

on: [push]

jobs:
  build_win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.0
          sdk: 10.0.17763.0

      - name: Install LuaVM
        run: |
          $ErrorActionPreference = "Stop"
          
          Invoke-WebRequest -OutFile LuaVM-0.5.4-vs2015-x64.exe https://github.com/xpol/luavm/releases/download/0.5.4/LuaVM-0.5.4-vs2015-x64.exe
          echo "Installing LuaVM"
          Start-Process .\LuaVM-0.5.4-vs2015-x64.exe -argumentlist "/verysilent" -Wait 
          echo "Install Finished"
          $env:Path += ";" + $env:LOCALAPPDATA + "\LuaVM;" + $env:LOCALAPPDATA + "\LuaVM\externals\bin;" + $env:LOCALAPPDATA + "\LuaVM\versions\5.3" 
          luavm use 5.3 
          echo $env:LOCALAPPDATA"\LuaVM;"$env:LOCALAPPDATA"\LuaVM\externals\bin;"$env:LOCALAPPDATA"\LuaVM\versions\5.3" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append


      - name: Copy Libs
        run: |
          $ErrorActionPreference = "Stop" 

          Copy-Item externals/bin/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\bin" -Recurse -Force
          Copy-Item externals/lib/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\lib" -Recurse -Force
          Copy-Item externals/include/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\include" -Recurse -Force

      # - name: Build lanes
      #   run: |
      #     luarocks install lanes

      - name: Build rings
        run: |
          luarocks install rings

      - name: Build coxpcall
        run: |
          luarocks install coxpcall

      - name: Build lua-curl
        run: |
          luarocks install lua-curl  CC="CL -DCURL_STATICLIB" LD="link wldap32.lib zlibstatic.lib"

      - name: Build luafft
        run: |
          luarocks install rockspecs/luafft-1.2-1.rockspec

      - name: Build luatz
        run: |
          luarocks install luatz

      - name: Build middleclass
        run: |
          luarocks install middleclass

      - name: Build lustache
        run: |
          luarocks install lustache

      - name: Build moses
        run: |
          luarocks install moses

      - name: Build luafun
        run: |
          luarocks install rockspecs/fun-0.1.3-1.rockspec

      - name: Build MD5
        run: |
          luarocks install MD5

      - name: Build copas
        run: |
          luarocks install copas

      - name: Build timerwheel
        run: |
          luarocks install timerwheel

      - name: Build binaryheap
        run: |
          luarocks install binaryheap

      - name: Build xavante
        run: |
          luarocks install xavante

      - name: Build lyaml
        run: |
          luarocks install rockspecs/lyaml-6.1.3-2.rockspec

      - name: Build lua-protobuf
        run: |
          luarocks install rockspecs/lua-protobuf-0.3.4-1.rockspec

      - name: Build luasql-firebird
        run: |
          luarocks install rockspecs/luasql-firebird-2.6.0-1.rockspec

      - name: Build luasql-postgres
        run: |
          luarocks install rockspecs/luasql-postgres-2.6.0-1.rockspec

      - name: Build luasql-sqlite3
        run: |
          luarocks install rockspecs/luasql-sqlite3-2.6.0-1.rockspec

      - name: Build luasql-odbc
        run: |
          luarocks install rockspecs\luasql-odbc-2.6.0-1.rockspec

      - name: Build lrexlib-pcre
        run: |
           luarocks install lrexlib-pcre CC="CL -DPCRE_STATIC"

      - name: Build stdlib
        run: |
          luarocks install stdlib

      - name: Build luaexpat
        run: |
          luarocks unpack luaexpat
          pushd .
          cd luaexpat-1.4.1-1\luaexpat\
          patch -p1 -i ..\..\patches\luaexpat.patch --binary
          luarocks make .\luaexpat-1.4.1-1.rockspec
          popd

      - name: Build luasec
        run: |
          luarocks install rockspecs/luasec-1.1.0-1.rockspec  

      - name: Build Lua-Zip
        run: |
          luarocks install rockspecs/lua-zip-0.2-0.rockspec 

      - name: Build LuaSocket
        run: |
           luarocks install luasocket

      - name: Build Lpeg
        run: |
          luarocks install lpeg

      - name: Build luafilesystem
        run: |
          luarocks install luafilesystem

      - name: Build Lua-cjson
        run: |
          git clone https://github.com/mpx/lua-cjson
          patch lua-cjson/lua_cjson.c  patches/lua-cjson.patch --binary
          pushd .
          cd lua-cjson
          luarocks make
          popd

      - name: Build Penlight
        run: |
          luarocks install penlight

      - name: Build Lua-Zlib
        run: |
          luarocks install rockspecs/lua-zlib-1.2-2.rockspec 

      - name: Build ZipWriter
        run: |
           luarocks install ZipWriter

      - name: Build luatz
        run: |
          luarocks install luatz

      - name: Build dkjson
        run: |
          luarocks install dkjson

      - name: Build lxsh
        run: |
          luarocks install lxsh





      - name: Collect files
        if: always()
        run: |
          mkdir archive
          mkdir archive\bin
          mkdir archive\lua
          mkdir archive\share
          mkdir archive\tests
          # mkdir archive\luavm
          cp "batteries_header.lua" archive
          cp -r bin\* archive\bin
          cp -r lua\* archive\lua
          cp -r  $env:LOCALAPPDATA"\LuaVM\versions\5.3\cmod\*" archive\bin
          cp -r   $env:LOCALAPPDATA"\LuaVM\versions\5.3\lua\*" archive\lua
          cp -r  tests/* archive/tests
          # cp -r  $env:LOCALAPPDATA"\LuaVM\externals archive\luavm
          Remove-Item archive\lua\luarocks -Recurse

      - name: Upload windows artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Mavriq-Lua-Batteries(win)
          path: archive