name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v4

    - name: setup 
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks install luaossl

    - name: test
      run: |
        busted -o utfTerminal
