name: Build

on: [push]

jobs:
  build_win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.0
          sdk: 10.0.17763.0


      - name: Cache LuaVM
        id: cache-luavm
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\LUAVM
          key: ${{ runner.os }}-luavm-
          restore-keys: |
            ${{ runner.os }}-luavm-

      - name: Install LuaVM
        if: steps.cache-luavm.outputs.cache-hit != 'true'
        run: |
          $ErrorActionPreference = "Stop"
          
          Invoke-WebRequest -OutFile LuaVM-0.5.4-vs2015-x64.exe https://github.com/xpol/luavm/releases/download/0.5.4/LuaVM-0.5.4-vs2015-x64.exe
          echo "Installing LuaVM"
          Start-Process .\LuaVM-0.5.4-vs2015-x64.exe -argumentlist "/verysilent" -Wait 
          echo "Install Finished"


      - name: Setup LuaVM    
        run: |
          $env:Path += ";" + $env:LOCALAPPDATA + "\LuaVM;" + $env:LOCALAPPDATA + "\LuaVM\externals\bin;" + $env:LOCALAPPDATA + "\LuaVM\versions\5.3" 
          luavm use 5.3 
          lua -v
          echo $env:LOCALAPPDATA"\LuaVM;"$env:LOCALAPPDATA"\LuaVM\externals\bin;"$env:LOCALAPPDATA"\LuaVM\versions\5.3" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append


      - name: Copy Libs
        run: |
          $ErrorActionPreference = "Stop" 

          Copy-Item externals/bin/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\bin" -Recurse -Force
          Copy-Item externals/lib/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\lib" -Recurse -Force
          Copy-Item externals/include/* -Destination $env:LOCALAPPDATA"\LuaVM\externals\include" -Recurse -Force

      # - name: Build lanes
      #   run: |
      #     luarocks install lanes

      # - name: Setup Sccache
      #   run: |
      #     scoop install sccache

      - name: Cache wxwidgets
        id: cache-wxwidgets
        uses: actions/cache@v3
        with:
          path: wxWidgets
          key: ${{ runner.os }}-wxwidgets-
          restore-keys: |
            ${{ runner.os }}-wxwidgets-

      - name: Build wxWidgets
        if: steps.cache-wxwidgets.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -OutFile wxWidgets-3.1.6.zip https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.6/wxWidgets-3.1.6.zip
          7z x -owxWidgets wxWidgets-3.1.6.zip
          cd wxWidgets\build\msw\
          nmake -f makefile.vc SHARED=0 UNICODE=1 BUILD=release TARGET_CPU=AMD64

      - name: Cache wxlua
        id: cache-wxlua
        uses: actions/cache@v3
        with:
          path: wxlua
          key: ${{ runner.os }}-wxlua-
          restore-keys: |
            ${{ runner.os }}-wxlua-


      - name: Build wxlua
        if: steps.cache-wxlua.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/pkulchenko/wxlua
          patch wxlua/wxlua/modules/luamodule/luamodule.cpp patches/wxlua.patch --binary
          mkdir wxlua/wxlua/wxlua-build
          pushd .
          cd wxlua/wxlua/wxlua-build
          cmake .. -DCMAKE_BUILD_TYPE=Release  -DwxWidgets_ROOT_DIR="$env:GITHUB_WORKSPACE"/wxWidgets/ -DwxLua_LUA_LIBRARY_USE_BUILTIN=false -DwxLua_LUA_INCLUDE_DIR="$env:LOCALAPPDATA"\LUAVM\versions\5.3\include -DwxLua_LUA_LIBRARY="$env:LOCALAPPDATA"\LUAVM\versions\5.3\lua53.lib
          cmake --build . --config Release
          cp bin/Release/wx.dll $env:LOCALAPPDATA"\LuaVM\versions\5.3\cmod"
          popd
          mkdir tests/wxlua
          mkdir docs/wxlua
          cp wxlua/wxlua/samples/* tests/wxlua
          cp wxlua/wxlua/docs/* docs/wxlua

      - name: Build LuaSocket
        run: |
          luarocks unpack luasocket
          luarocks install luasocket
          mkdir docs/luasocket
          cp luasocket-3.0.0-1/luasocket/docs/* docs/luasocket
          cp luasocket-3.0.0-1/luasocket/README.md docs/luasocket
          cp luasocket-3.0.0-1/luasocket/LICENSE docs/luasocket

      - name: Build timerwheel
        run: |
          luarocks unpack timerwheel
          luarocks install timerwheel
          mkdir docs/timerwheel
          cp timerwheel-0.2.0-2/timerwheel.lua/docs/*  docs/luasocket
          cp timerwheel-0.2.0-2/timerwheel.lua/README.md  docs/luasocket
          cp timerwheel-0.2.0-2/timerwheel.lua/LICENSE  docs/luasocket

      - name: Build binaryheap
        run: |
          luarocks unpack binaryheap
          luarocks install binaryheap
          mkdir docs/binaryheap
          cp binaryheap-0.4-1/binaryheap.lua-version_0v4/docs/*  docs/binaryheap
          cp binaryheap-0.4-1/binaryheap.lua-version_0v4/README.md  docs/binaryheap
          Invoke-WebRequest  https://raw.githubusercontent.com/Tieske/binaryheap.lua/master/LICENSE   -OutFile  docs/binaryheap/LICENSE

      - name: Build luafilesystem
        run: |
          luarocks unpack luafilesystem
          luarocks install luafilesystem
          mkdir docs/luafilesystem
          cp luafilesystem-1.8.0-1/luafilesystem/doc/us/*  docs/luafilesystem
          cp luafilesystem-1.8.0-1/luafilesystem/README.md  docs/luafilesystem
          cp luafilesystem-1.8.0-1/luafilesystem/LICENSE  docs/luafilesystem

      - name: Build copas
        run: |
          luarocks unpack rockspecs/copas-3.0.0-3.rockspec
          luarocks install rockspecs/copas-3.0.0-3.rockspec
          patch $env:LOCALAPPDATA"\LUAVM\versions\5.3\lua\copas.lua"  patches/copas.lua.patch
          mkdir docs/copas
          cp copas-3.0.0-3/copas/docs/* docs/copas 
          cp copas-3.0.0-3/copas/LICENSE docs/copas
          cp copas-3.0.0-3/copas/README.md docs/copas

      - name: Build coxpcall
        run: |
          luarocks unpack coxpcall
          luarocks install coxpcall
          mkdir docs/coxpcall
          cp coxpcall-1.17.0-1/coxpcall/doc/* docs/coxpcall
          cp coxpcall-1.17.0-1/coxpcall/README.md docs/coxpcall
          
      - name: Build CopasTimer
        run: |
          luarocks install CopasTimer

      - name: Build lub
        run: |
          luarocks install lub

      - name: Build vstruct
        run: |
          luarocks install vstruct

      - name: Build lbase64
        run: |
          luarocks install lbase64

      - name: Build rs232
        run: |
          luarocks install rs232

      - name: Build rings
        run: |
          luarocks install rings

      - name: Build lua-curl
        run: |
          luarocks install lua-curl  CC="CL -DCURL_STATICLIB" LD="link wldap32.lib zlibstatic.lib"

      - name: Build luafft
        run: |
          luarocks install rockspecs/luafft-1.2-1.rockspec

      - name: Build luatz
        run: |
          luarocks install luatz

      - name: Build middleclass
        run: |
          luarocks install middleclass

      - name: Build lustache
        run: |
          luarocks install lustache

      - name: Build moses
        run: |
          luarocks install moses

      - name: Build luafun
        run: |
          luarocks install rockspecs/fun-0.1.3-1.rockspec

      - name: Build MD5
        run: |
          luarocks install MD5

      - name: Build xavante
        run: |
          luarocks install xavante

      - name: Build lyaml
        run: |
          luarocks install rockspecs/lyaml-6.1.3-2.rockspec

      - name: Build lua-protobuf
        run: |
          luarocks install rockspecs/lua-protobuf-0.3.4-1.rockspec

      - name: Build luasql-mysql
        run: |
          luarocks unpack rockspecs\luasql-mysql-2.6.0-1.rockspec
          patch luasql-mysql-2.6.0-1/luasql/src/luasql.h  patches/luasql-mysql.patch --binary
          cd luasql-mysql-2.6.0-1/luasql/
          luarocks make ../../rockspecs\luasql-mysql-2.6.0-1.rockspec

      - name: Build luasql-firebird
        run: |
          luarocks install rockspecs/luasql-firebird-2.6.0-1.rockspec

      - name: Build luasql-postgres
        run: |
          luarocks install rockspecs/luasql-postgres-2.6.0-1.rockspec

      - name: Build luasql-sqlite3
        run: |
          luarocks install rockspecs/luasql-sqlite3-2.6.0-1.rockspec

      - name: Build luasql-odbc
        run: |
          luarocks install rockspecs\luasql-odbc-2.6.0-1.rockspec

      - name: Build lrexlib-pcre
        run: |
           luarocks install lrexlib-pcre CC="CL -DPCRE_STATIC"

      - name: Build stdlib
        run: |
          luarocks install stdlib

      - name: Build luaexpat
        run: |
          luarocks unpack luaexpat
          pushd .
          cd luaexpat-1.4.1-1\luaexpat\
          patch -p1 -i ..\..\patches\luaexpat.patch --binary
          luarocks make .\luaexpat-1.4.1-1.rockspec
          popd

      - name: Build luasec
        run: |
          luarocks install rockspecs/luasec-1.1.0-1.rockspec  

      - name: Build Lua-Zip
        run: |
          luarocks install rockspecs/lua-zip-0.2-0.rockspec 

      - name: Build Lpeg
        run: |
          luarocks install lpeg

      - name: Build Lua-cjson
        run: |
          git clone https://github.com/mpx/lua-cjson
          patch lua-cjson/lua_cjson.c  patches/lua-cjson.patch --binary
          pushd .
          cd lua-cjson
          luarocks make
          popd

      - name: Build Penlight
        run: |
          luarocks install penlight

      - name: Build Lua-Zlib
        run: |
          luarocks install rockspecs/lua-zlib-1.2-2.rockspec 

      - name: Build ZipWriter
        run: |
           luarocks install ZipWriter

      - name: Build luatz
        run: |
          luarocks install luatz

      - name: Build dkjson
        run: |
          luarocks install dkjson

      - name: Build lxsh
        run: |
          luarocks install lxsh





      - name: Collect files
        if: always()
        run: |
          mkdir archive
          mkdir archive\bin
          mkdir archive\lua
          mkdir archive\docs
          mkdir archive\tests
          # mkdir archive\luavm
          cp "batteries_header.lua" archive
          cp -r bin\* archive\bin
          cp -r lua\* archive\lua
          cp -r docs\* archive\docs
          cp -r  $env:LOCALAPPDATA"\LuaVM\versions\5.3\cmod\*" archive\bin
          cp -r   $env:LOCALAPPDATA"\LuaVM\versions\5.3\lua\*" archive\lua
          cp -r  tests/* archive/tests
          # cp -r  $env:LOCALAPPDATA"\LuaVM\externals archive\luavm
          Remove-Item archive\lua\luarocks -Recurse

      - name: Upload windows artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Mavriq-Lua-Batteries(win)
          path: archive