name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: setup 
      run: |
        # curl -sSL -o LuaVM-0.5.0-vs2015-x64.exe https://github.com/xpol/luavm/releases/download/0.5.4/LuaVM-0.5.4-vs2015-x64.exe
        Invoke-WebRequest -OutFile LuaVM-0.5.4-vs2015-x64.exe https://github.com/xpol/luavm/releases/download/0.5.4/LuaVM-0.5.4-vs2015-x64.exe
        pwd
        ls
        echo "starting install"
        Start-Process .\LuaVM-0.5.4-vs2015-x64.exe -argumentlist "/verysilent" -Wait 
        echo "install finished"
        $env:Path += ";%LocalAppData%\LuaVM;"
        luarocks install busted
        luarocks install moonscript
        luarocks install luaossl
