name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: setup 
      run: |
        curl -sSL -o LuaVM-0.5.0-vs2015-x64.exe https://dl.bintray.com/xpol/luavm/LuaVM-0.5.0-vs2015-x64.exe
        # LuaVM-vs2015-x64.exe /verysilent
        # set PATH=%LocalAppData%\LuaVM;%PATH%
        # luarocks install busted
        # luarocks install moonscript
        # luarocks install luaossl
